server:
  port: 8081

logging:
  level:
    web: info
    cloud: info

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL} #http://localhost:8761/eureka/

spring:
  application:
    name: auth-service

  datasource:
    username: ${DB_USERNAME} #root
    password: ${DB_PASSWORD} #9qwe1ox
    url: ${DB_URL} #jdbc:postgresql://localhost:5433/auth-service
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yml
    default-schema: auth
    liquibase-schema: liquibase

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: false
        show_sql: false
        default_schema: auth

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 240000 #4 min  # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

debug: false

# http://localhost:8081/swagger-ui/index.html
springdoc:
  override-with-generic-response: false
