server:
  port: 8080

logging:
  level:
    web: info
    cloud: info

eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: ${EUREKA_SERVER_URL} #http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**
#        - id: profile-service
#          uri: lb://profile-service
#          predicates:
#            - Path=/profile/**