server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL} #http://localhost:8761/eureka/

spring:
  application:
    name: account-management-service

  datasource:
    username: ${POSTGRES_USERNAME} #root
    password: ${POSTGRES_PASSWORD} #9qwe1ox
    url: ${POSTGRES_ACCOUNT_URL} #jdbc:postgresql://postgres-profile:5434/profile-service
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: false
        show_sql: false
        default_schema: account

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml
    default-schema: account
    liquibase-schema: liquibase

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: create-account-group
      auto-offset-reset: earliest