server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

spring:
  application:
    name: vivid-log-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
