server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

spring:
  application:
    name: logs-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
