server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL} #http://localhost:8761/eureka/

spring:
  application:
    name: profile-service

  datasource:
    username: ${DB_USERNAME} #root
    password: ${DB_PASSWORD} #9qwe1ox
    url: ${DB_URL} #jdbc:postgresql://postgres-profile:5434/profile-service
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml
    default-schema: profile
    liquibase-schema: liquibase

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}