server:
  port: 8088

logging:
  level:
    liquibase: INFO


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

spring:
  application:
    name: email-verify-service

  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_EMAIL_VERIFY_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: false
        show_sql: false
        default_schema: verify

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yml
    liquibase-schema: liquibase
    default-schema: verify

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: email-verify-group
