server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

spring:
  application:
    name: email-verify-sender-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: email-verify-group
      auto-offset-reset: earliest

  mail:
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true