server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

spring:
  application:
    name: email-verify-send-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
