name: Docker Image CI account-management-service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'account-management-service/**'

jobs:
  account-management-service:
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ vars.DOCKER_ACCESS_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build with Maven
      run: |
        cd account-management-service
        mvn clean package -DskipTests

    - name: Build Docker image
      run: |
        cd account-management-service
        docker build -t ${{ env.DOCKER_USERNAME }}/account-management-service:latest .

    - name: Push Docker image
      run: |
        cd account-management-service
        docker push ${{ env.DOCKER_USERNAME }}/account-management-service:latest
